// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzT1ygMyvhAowRwA8Wsnc2ON0jdahy_o',
    appId: '1:620918852537:web:8a9bc7ad1547ff0a018468',
    messagingSenderId: '620918852537',
    projectId: 'soulheads',
    authDomain: 'soulheads.firebaseapp.com',
    storageBucket: 'soulheads.firebasestorage.app',
    measurementId: 'G-TBSR1SZV87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8WTfxNtEHSHX7YxgyXL4RgJCuVKOQ1NQ',
    appId: '1:620918852537:android:211c94b3c21f1e31018468',
    messagingSenderId: '620918852537',
    projectId: 'soulheads',
    storageBucket: 'soulheads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1HRWqWmNjXD0dnHKBjUpab1Iid2CeCo',
    appId: '1:620918852537:ios:f71dc8c6749beb87018468',
    messagingSenderId: '620918852537',
    projectId: 'soulheads',
    storageBucket: 'soulheads.firebasestorage.app',
    iosClientId: '620918852537-foqela301278pto2kq2k6vsok9qrsfdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.solehead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1HRWqWmNjXD0dnHKBjUpab1Iid2CeCo',
    appId: '1:620918852537:ios:f71dc8c6749beb87018468',
    messagingSenderId: '620918852537',
    projectId: 'soulheads',
    storageBucket: 'soulheads.firebasestorage.app',
    iosClientId: '620918852537-foqela301278pto2kq2k6vsok9qrsfdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.solehead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgzT1ygMyvhAowRwA8Wsnc2ON0jdahy_o',
    appId: '1:620918852537:web:518ae340a83fe3cb018468',
    messagingSenderId: '620918852537',
    projectId: 'soulheads',
    authDomain: 'soulheads.firebaseapp.com',
    storageBucket: 'soulheads.firebasestorage.app',
    measurementId: 'G-CX3GFP8K0W',
  );
}
